/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#006e6e',
        'on-surface-variant': '#44474e',
        'inverse-on-surface': '#eaf1ff',
        'on-background': '#0b1c30',
        'secondary': '#006a6a',
        'surface-dim': '#cbdbf5',
        'on-error': '#ffffff',
        'tertiary': '#180500',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#ffdbcb',
        'on-secondary-fixed-variant': '#004f4f',
        'background': '#f8f9ff',
        'on-secondary-fixed': '#002020',
        'surface': '#f8f9ff',
        'on-primary-container': '#708ab5',
        'tertiary-container': '#3d1500',
        'primary': '#000a1e',
        'tertiary-fixed-dim': '#ffb691',
        'on-tertiary-fixed-variant': '#6c391d',
        'surface-container-highest': '#d3e4fe',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#2d476f',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#002147',
        'on-tertiary-container': '#b97958',
        'outline': '#74777f',
        'on-primary': '#ffffff',
        'inverse-surface': '#213145',
        'primary-fixed-dim': '#aec7f6',
        'error-container': '#ffdad6',
        'surface-container-low': '#eff4ff',
        'error': '#ba1a1a',
        'on-primary-fixed': '#001b3d',
        'surface-tint': '#465f88',
        'surface-container': '#e5eeff',
        'surface-variant': '#d3e4fe',
        'surface-container-high': '#dce9ff',
        'primary-fixed': '#d6e3ff',
        'secondary-fixed': '#93f2f2',
        'on-tertiary': '#ffffff',
        'outline-variant': '#c4c6cf',
        'surface-bright': '#f8f9ff',
        'secondary-container': '#90efef',
        'on-surface': '#0b1c30',
        'secondary-fixed-dim': '#76d6d5',
        'inverse-primary': '#aec7f6',
        'on-tertiary-fixed': '#341100',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xl: '32px',
        md: '16px',
        lg: '24px',
        base: '8px',
        sm: '8px',
        'sidebar-width': '260px',
        xs: '4px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
